import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
const root=process.env.DSH_SOURCE;
if(!root) throw new Error('Set DSH_SOURCE to the checked-out DSH repository');
const load=(p:string)=>import(pathToFileURL(path.join(root,p)).href);
const {interruptedTurnClosers,TOOL_NOT_STARTED,TOOL_OUTCOME_UNKNOWN}=await load('packages/core/session/src/repair.ts');
const {encodeSeqRanges,decodeSeqRanges}=await load('packages/core/session/src/seq-ranges.ts');
const {snapshotJsonValue,deepFreeze}=await load('packages/util/values/src/index.ts');
const event=(type:string,data:object,seq:number)=>({type,data,seq,time:1000+seq});
const start=[event('turn/start',{turn:0},0),event('step/start',{turn:0,step:0},1),event('assistant/message',{turn:0,step:0,message:{role:'assistant',content:[{type:'tool-call',id:'tc1',name:'demo',arguments:'{}'}]},stream:[]},2)];
const notStarted=interruptedTurnClosers(start as never);
assert.equal(notStarted[0].type,'tool/result');
assert.equal(notStarted[0].data.error.code,TOOL_NOT_STARTED);
assert.deepEqual(notStarted.map(e=>e.type),['tool/result','step/end','turn/end']);
console.log('PASS: requested but undispatched tool becomes TOOL_NOT_STARTED');
const begun=[...start,event('tool/call',{turn:0,step:0,callId:'tc1',name:'demo',arguments:'{}'},3)];
const unknown=interruptedTurnClosers(begun as never);
assert.equal(unknown[0].data.error.code,TOOL_OUTCOME_UNKNOWN);
assert.deepEqual(unknown[0].sourceEventSeqs,[3]);
assert.equal(unknown.at(-1).data.reason.kind,'interrupted');
assert.deepEqual(unknown.map(e=>e.seq),[4,5,6]);
console.log('PASS: started tool without durable result becomes outcome unknown, with source linkage');
assert.deepEqual(interruptedTurnClosers([...begun,...unknown] as never),[]);
console.log('PASS: recovery closers are idempotent for balanced repaired log');
const ids=[1,2,3,4,8,11,12,13];
assert.deepEqual(decodeSeqRanges(encodeSeqRanges(ids as never)),ids);
assert.throws(()=>decodeSeqRanges([[3,1]]));
console.log('PASS: source-sequence encoding round trip and invalid-range rejection');
const input={nested:{v:1}};const copy=deepFreeze(snapshotJsonValue(input));input.nested.v=2;
assert.equal(copy.nested.v,1);assert.ok(Object.isFrozen(copy.nested));
assert.equal(snapshotJsonValue({n:NaN}),undefined);
console.log('PASS: payload snapshot isolates caller mutation and rejects lossy JSON');
